CREATE TABLE Clinica (id_clinica int IDENTITY NOT NULL, nome varchar(255) NOT NULL, cidade varchar(255) NOT NULL, morada varchar(255) NOT NULL, email varchar(255) NOT NULL, PRIMARY KEY (id_clinica));
CREATE TABLE ConfiguracoesGerais (id_Configuracoes int IDENTITY NOT NULL, id_clinica int NOT NULL, max_faturas_atraso int NULL, PRIMARY KEY (id_Configuracoes));
CREATE TABLE Consulta (id_consulta int IDENTITY NOT NULL, id_utilizador_utente int NOT NULL, id_utilizador_profissional_saude int NOT NULL, id_clinica int NOT NULL, id_especialidade_consulta int NOT NULL, id_tratamento int NULL, id_protocolo int NOT NULL, id_gabinete int NOT NULL, data datetime NOT NULL, preco float(10) NOT NULL, urgente bit NOT NULL, domicilio bit NOT NULL, PRIMARY KEY (id_consulta));
CREATE TABLE Documento (id_documento int IDENTITY NOT NULL, id_utilizador int NOT NULL, documento image NOT NULL, PRIMARY KEY (id_documento));
CREATE TABLE EspecialidadeConsulta (id_especialidade_consulta int IDENTITY NOT NULL, especialidade varchar(255) NOT NULL, preco float(10) NOT NULL, PRIMARY KEY (id_especialidade_consulta));
CREATE TABLE Extra (id_extra int IDENTITY NOT NULL, id_consulta int NOT NULL, preco float(10) NOT NULL, descricao varchar(255) NOT NULL, PRIMARY KEY (id_extra));
CREATE TABLE Fatura (id_fatura int IDENTITY NOT NULL, id_consulta int NOT NULL, data_emissao datetime NOT NULL, descricao varchar(255) NOT NULL, preco float(10) NOT NULL, pago bit NOT NULL, PRIMARY KEY (id_fatura));
CREATE TABLE Gabinete (id_gabinete int IDENTITY NOT NULL, id_clinica int NOT NULL, numero_porta varchar(255) NOT NULL, PRIMARY KEY (id_gabinete));
CREATE TABLE LinhaFatura (id_linhaFatura int IDENTITY NOT NULL, id_fatura int NOT NULL, preco float(10) NOT NULL, PRIMARY KEY (id_linhaFatura));
CREATE TABLE Login (id_login int IDENTITY NOT NULL, id_utilizador int NOT NULL, pasword varchar(255) NOT NULL, email varchar(255) NOT NULL, PRIMARY KEY (id_login));
CREATE TABLE Notificacao (id_notificacao int IDENTITY NOT NULL, id_consulta int NOT NULL, notificacao varchar(255) NOT NULL, data datetime NOT NULL, PRIMARY KEY (id_notificacao));
CREATE TABLE Protocolo (id_protocolo int IDENTITY NOT NULL, protocolo varchar(255) NOT NULL, PRIMARY KEY (id_protocolo));
CREATE TABLE ProtocoloUtilizador (id_utilizador int NOT NULL, id_protocolo int NOT NULL, PRIMARY KEY (id_utilizador, id_protocolo));
CREATE TABLE Tipo (id_utilizador int NOT NULL, id_tipoUtilizador int NOT NULL, PRIMARY KEY (id_utilizador, id_tipoUtilizador));
CREATE TABLE TipoUtilizador (id_tipoUtilizador int IDENTITY NOT NULL, tipo varchar(255) NOT NULL, PRIMARY KEY (id_tipoUtilizador));
CREATE TABLE Tratamento (id_tratamento int IDENTITY NOT NULL, id_utilizador_utente int NOT NULL, id_utilizador_profissional_saude int NOT NULL, data datetime NOT NULL, recorrencia varchar(255) NOT NULL, PRIMARY KEY (id_tratamento));
CREATE TABLE Utilizador (id_utilizador int IDENTITY NOT NULL, nome varchar(255) NOT NULL, data_nascimento datetime NOT NULL, cidade varchar(255) NULL, morada varchar(255) NOT NULL, nif int NOT NULL, iban int NOT NULL, telemovel int NOT NULL, tem_reponsavel bit NOT NULL, PRIMARY KEY (id_utilizador));
ALTER TABLE Tipo ADD CONSTRAINT FKTipo707132 FOREIGN KEY (id_utilizador) REFERENCES Utilizador (id_utilizador);
ALTER TABLE Tipo ADD CONSTRAINT FKTipo627619 FOREIGN KEY (id_tipoUtilizador) REFERENCES TipoUtilizador (id_tipoUtilizador);
ALTER TABLE ProtocoloUtilizador ADD CONSTRAINT FKProtocoloU119160 FOREIGN KEY (id_utilizador) REFERENCES Utilizador (id_utilizador);
ALTER TABLE ProtocoloUtilizador ADD CONSTRAINT FKProtocoloU513558 FOREIGN KEY (id_protocolo) REFERENCES Protocolo (id_protocolo);
ALTER TABLE Documento ADD CONSTRAINT FKDocumento357513 FOREIGN KEY (id_utilizador) REFERENCES Utilizador (id_utilizador);
ALTER TABLE Consulta ADD CONSTRAINT FKConsulta17567 FOREIGN KEY (id_utilizador_utente) REFERENCES Utilizador (id_utilizador);
ALTER TABLE Consulta ADD CONSTRAINT FKConsulta913093 FOREIGN KEY (id_utilizador_profissional_saude) REFERENCES Utilizador (id_utilizador);
ALTER TABLE Consulta ADD CONSTRAINT FKConsulta790238 FOREIGN KEY (id_clinica) REFERENCES Clinica (id_clinica);
ALTER TABLE Extra ADD CONSTRAINT FKExtra879209 FOREIGN KEY (id_consulta) REFERENCES Consulta (id_consulta);
ALTER TABLE Consulta ADD CONSTRAINT FKConsulta895404 FOREIGN KEY (id_especialidade_consulta) REFERENCES EspecialidadeConsulta (id_especialidade_consulta);
ALTER TABLE Notificacao ADD CONSTRAINT FKNotificaca996980 FOREIGN KEY (id_consulta) REFERENCES Consulta (id_consulta);
ALTER TABLE Gabinete ADD CONSTRAINT FKGabinete54453 FOREIGN KEY (id_clinica) REFERENCES Clinica (id_clinica);
ALTER TABLE LinhaFatura ADD CONSTRAINT FKLinhaFatur252906 FOREIGN KEY (id_fatura) REFERENCES Fatura (id_fatura);
ALTER TABLE Fatura ADD CONSTRAINT FKFatura903774 FOREIGN KEY (id_consulta) REFERENCES Consulta (id_consulta);
ALTER TABLE Consulta ADD CONSTRAINT FKConsulta916013 FOREIGN KEY (id_tratamento) REFERENCES Tratamento (id_tratamento);
ALTER TABLE Login ADD CONSTRAINT FKLogin697016 FOREIGN KEY (id_utilizador) REFERENCES Utilizador (id_utilizador);
ALTER TABLE ConfiguracoesGerais ADD CONSTRAINT FKConfigurac420648 FOREIGN KEY (id_clinica) REFERENCES Clinica (id_clinica);
